environment:
  NuGetApiKey:
    secure: w6ByYlL09UawyqLUgynpzA==

# Allow WMF5 (i.e. PowerShellGallery functionality)
os: WMF 5

skip_commits:
  message: /updated readme.*|update readme.*s/

build: false

test-script:
  - ps: . .\Build.ps1